apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-target-updater.clusterRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-target-updater.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-target-updater.serviceAccountName" . }}
  namespace: {{ include "ingress-target-updater.namespace" .}}