apiVersion: batch/v1
kind: CronJob
metadata:
  name: ingress-target-updater
  namespace: ingress-target-updater
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ingress-target-updater
          restartPolicy: OnFailure
          containers:
          - name: ingress-target-updater
            image: ebmba/ingress-target-updater:latest
            imagePullPolicy: IfNotPresent
            # args:
            # - --api-url="https://api.ipify.org?format=json"
            # - --target-annotation-key="external-dns.alpha.kubernetes.io/target"
            # - --filter-label-key="ingress-target-updater"
            # - --filter-label-value="true"