apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-target-updater
  namespace: ingress-target-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-target-updater-clusterrole
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-target-updater-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-target-updater-clusterrole
subjects:
- kind: ServiceAccount
  name: ingress-target-updater
  namespace: ingress-target-updater
---